[package]
name = "segvec"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = ["Jacob McCollum <jacob.r.mccollum@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mccolljr/segvec/"

[dev-dependencies]
rand = "0.8.4"
