name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Run cargo check (default features)
        run: <<
          cargo check --verbose;
          cargo check --features small-vec;
      - name: Run tests
        run: <<
          cargo test --verbose;
          cargo test --features small-vec --verbose;
